package uk.gov.hmcts.ccd.corecasedata.scenarios

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import java.io.{BufferedWriter, FileWriter}
import uk.gov.hmcts.ccd.corecasedata.scenarios.utils.Environment

object CreateUser {

  val MinThinkTime = Environment.minThinkTime
  val MaxThinkTime = Environment.maxThinkTime
  val CommonHeader = Environment.commonHeader
  val CCDAPIEnvurl = Environment.baseURL
//  val feedUserData = csv("CaseSharingUsers_Small.csv")
  val idamAdminFeeder = csv("IdamAdmin.csv")
  val feedUserData = csv("RolesForUsers.csv")
  val divUserData = csv("DivorceSolUserData.csv")
  val roleFeeder = csv("RolesToAdd.csv").circular
  val numberFeeder = csv("NumberList.csv").circular

  val headers_1 = Map( //ServiceAuthorization token can be called from http://rpe-service-auth-provider-perftest.service.core-compute-perftest.internal/testing-support/lease
    "Content-Type" -> "application/json",
    "Accept" -> "application/json")

  val IdamAdminLogin =

    feed(idamAdminFeeder)

    .exec(http("AdminLogin")
      .post(Environment.idamAPI + "/loginUser")
      .header("accept", "application/json")
      .header("Content-Type", "application/x-www-form-urlencoded")
      .formParam("password", "${password}")
      .formParam("username", "${email}")
      .check(jsonPath("$.api_auth_token").saveAs("authToken")))

  val headers_0 = Map( //Authorization token needs to be generated by User Login
    "Authorization" -> "AdminApiAuthToken ${authToken}",
    "Content-Type" -> "application/json")

  val IdamUser = feed(divUserData)

    .exec(http("GetUserID")
      .get(Environment.idamAPI + "/users?email=${DivorceUserName}")
      .headers(headers_0)
      .check(jsonPath("$.id").saveAs("userId"))
      .check(status.saveAs("statusvalue")))

    //Outputs the user email and idam id to a CSV, can be commented out if not needed  
    .doIf(session=>session("statusvalue").as[String].contains("200")) {
      exec {
        session =>
          val fw = new BufferedWriter(new FileWriter("EmailAndIdamIDs.csv", true))
          try {
            fw.write(session("DivorceUserName").as[String] + ","+session("userId").as[String] + "\r\n")
          }
          finally fw.close()
          session
      }
    }

  val GetAndApplyRole = feed(roleFeeder)

    .exec(http("GetRole_${role}")
      .get(Environment.idamAPI + "/roles/name/${role}")
      .headers(headers_0)
      .check(jsonPath("$.id").saveAs("roleId")))

    .exec(http("ApplyRole_${role}")
      .patch(Environment.idamAPI + "/users/${userId}/roles/${roleId}")
      .headers(headers_0))

    .exec {
      session =>
        println(session("email").as[String])
        println(session("role").as[String])
        session
    }

    .pause(1)

  val GetAndRemoveRole = feed(roleFeeder)

    .exec(http("GetRole_${role}") //${role}
      .get(Environment.idamAPI + "/roles/name/${role}") //${role}
      .headers(headers_0)
      .check(jsonPath("$.id").saveAs("roleId")))

    .exec(http("DenyRole_${role}") //${role}
      .delete(Environment.idamAPI + "/users/${userId}/roles/${roleId}")
      .headers(headers_0))

    .exec {
      session =>
        println(session("email").as[String])
        println(session("role").as[String])
        session
    }

    .pause(1)


//   val DeleteUser = feed(feedDeleteData)

// //    exec(http("DeleteIdamUser")
// //      .delete(Environment.idamAPI + "/users/${userId}")
// //      .headers(headers_0))

//     .exec(http("DeleteUser")
//       .delete(Environment.idamAPI + "/testing-support/accounts/${Email}")
//       .headers(headers_1))

//       .exec {
//       session =>
//         println(session("Email").as[String])
//         session
//     }

  val CreateUserProfile = feed(feedUserData)

    .exec(http("request_4")
      .post("http://ccd-user-profile-api-perftest.service.core-compute-perftest.internal/user-profile/users")
      .headers(headers_1)
      .body(StringBody("{\n    \"id\": \"${CCDUserName}\",\n    \"jurisdictions\": [{\"id\": \"DIVORCE\"},{\"id\": \"AUTOTEST1\"},{\"id\": \"CMC\"},{\"id\": \"PROBATE\"},{\"id\": \"SSCS\"},{\"id\": \"TRIBUNALS\"},{\"id\": \"EMPLOYMENT\"}],\n    \"work_basket_default_jurisdiction\": \"DIVORCE\",\n    \"work_basket_default_case_type\": \"DIVORCE\",\n    \"work_basket_default_state\": \"Submitted\"\n}")))

    // .exec {
    //   session =>
    //     println(session("CCDUserName").as[String])
    //     session
    // }

    .pause(1)

  val CreateUserInIdam =

    feed(numberFeeder)

    .exec(http("CreateUser")
      .post(Environment.idamAPI + "/testing-support/accounts")
      .header("Content-Type", "application/json")
      .body(ElFileBody("Idam_CreateUserBody.json")))

    //Outputs the user email and idam id to a CSV, can be commented out if not needed  
    .exec {
      session =>
        val fw = new BufferedWriter(new FileWriter("CreatedIdamUsers.csv", true))
        try {
          fw.write("PerfTest_SeniorTribunal_" + session("userNumber").as[String] + "@justice.gov.uk" + "\r\n")
        }
        finally fw.close()
        session
    }

  val DeleteUserInIdam =

    feed(feedUserData)

    .exec(http("DeleteUser")
      .delete(Environment.idamAPI + "/testing-support/accounts/${email}")
      .header("Content-Type", "application/json")
      .header("Accept", "application/json"))

}